---
galaxy_info:
  author: Boundless Team
  description: Ansible role for installing and configuring MinIO S3-compatible object storage
  license: Apache-2.0
  min_ansible_version: '2.9'
  galaxy_tags:
    - storage
    - s3
    - minio

dependencies: []
