---
galaxy_info:
  author: Boundless
  description: Install and configure Boundless Broker service
  license: license (BSD, MIT)
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - boundless
    - broker
    - systemd

dependencies: []
