---
galaxy_info:
  author: Boundless
  description: Install and configure PostgreSQL database
  license: license (BSD, MIT)
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - database
    - postgresql
    - systemd

dependencies: []
