[package]
name = "bento-client"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[[bin]]
name = "bento_cli"
path = "src/bento_cli.rs"

[dependencies]
anyhow = { workspace = true }
bincode = "1.3.3"
bonsai-sdk = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true, features = ["env", "derive"] }
reqwest = { version = "0.12", features = ["json"] }
risc0-zkvm = { workspace = true }
sample-guest-common = { workspace = true }
sample-guest-methods = { workspace = true }
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
serde_json = { workspace = true }
