[market]
min_mcycle_price = "0.000000025"
lookback_blocks = 300
min_mcycle_price_collateral_token = "0"
peak_prove_khz = 8000
priority_requestor_lists = [
    "https://requestors.boundless.network/boundless-recommended-priority-list.standard.json",
]
allow_requestor_lists = [
    "https://requestors.boundless.network/boundless-allowed-list.json"
]
max_collateral = "200"
balance_warn_threshold = "0.05"
balance_error_threshold = "0.01"
collateral_balance_warn_threshold = "100"
collateral_balance_error_threshold = "50"
max_concurrent_preflights = 4
max_concurrent_proofs = 2
max_journal_bytes = 20000
max_file_size = 500000000000
max_mcycle_limit = 500000000000
