[market]
min_mcycle_price = "0.000000025"
expected_probability_win_secondary_fulfillment = 100 # assume we win all secondary fulfillments -> min_mcycle_price is used to judge whether to accept a request or not
lookback_blocks = 300
peak_prove_khz = 8000
priority_requestor_lists = [
    "https://requestors.boundless.network/boundless-recommended-priority-list.standard.json",
    "https://requestors.boundless.network/boundless-recommended-priority-list.large.json",
]
max_collateral = "200"
balance_warn_threshold = "0.05"
balance_error_threshold = "0.01"
collateral_balance_warn_threshold = "100"
collateral_balance_error_threshold = "50"
max_concurrent_preflights = 25
max_concurrent_proofs = 2
max_journal_bytes = 20000
max_file_size = 500000000000
max_mcycle_limit = 500000000000
