---
galaxy_info:
  author: Boundless
  description: Install and configure Boundless Miner service
  license: BSD
  min_ansible_version: '2.9'
  galaxy_tags:
    - miner
    - boundless
    - bento
dependencies: []
