[package]
name = "workflow-zkvm-sp1"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[dependencies]
anyhow = { workspace = true }
async-trait = "0.1"
bincode = { workspace = true }
inventory = "0.3"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sp1-sdk = "5.2.4"
taskdb = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
workflow = { workspace = true }
workflow-common = { workspace = true }

