[package]
name = "workflow"
resolver = "2"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
publish = false

[package.metadata.release]
release = false

[features]
default = []
cuda = ["risc0-zkvm/cuda", "blake3_groth16/cuda"]

[dependencies]
async-trait = "0.1"
anyhow = { workspace = true }
bincode = { workspace = true }
blake3_groth16 = { workspace = true, features = ["prove"] }
bytemuck = { workspace = true }
clap = { workspace = true, features = ["env", "derive"] }
deadpool-redis = { workspace = true }
hex = { workspace = true }
inventory = "0.3"
nix = { version = "0.29", features = ["fs"] }
prometheus = { workspace = true }
prometheus_exporter = { workspace = true }
rand = { workspace = true }
redis = { workspace = true, features = ["tokio-rustls-comp", "tokio-comp"] }
risc0-binfmt = { workspace = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["prove"] }
serde = { workspace = true }
serde_json = { workspace = true }
signal-hook = "0.3"
sqlx = { workspace = true }
taskdb = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true, features = ["process"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
uuid = { workspace = true }
workflow-common = { workspace = true }
