---
# Valkey installation
valkey_install: true

# Valkey service configuration
valkey_service_enabled: true
valkey_service_state: started

# Valkey configuration
valkey_host: "localhost"
valkey_port: 6379
valkey_protected_mode: false
valkey_maxmemory: "12gb"
valkey_maxmemory_policy: "allkeys-lru"
