---
galaxy_info:
  author: Boundless
  description: Install and configure Valkey (Redis fork) server
  license: license (BSD, MIT)
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - cache
    - valkey
    - redis
    - systemd

dependencies: []
