---
- name: Restart PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: "{{ postgresql_service_enabled | bool }}"

- name: Reload PostgreSQL service
  ansible.builtin.systemd:
    name: postgresql
    state: reloaded
    enabled: "{{ postgresql_service_enabled | bool }}"
