---
galaxy_info:
  author: Boundless
  description: Install Rust programming language
  license: license (BSD, MIT)
  min_ansible_version: '2.9'
  galaxy_tags:
    - rust
    - programming
    - compiler

dependencies: []
